# Generated by Django 2.0.5 on 2018-06-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('line', models.CharField(max_length=20)),
                ('fr_code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('fr_code',),
            },
        ),
        migrations.CreateModel(
            name='SubwayLandmarkPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.Subway')),
            ],
        ),
    ]
