# Generated by Django 2.0.5 on 2018-09-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20)),
                ('admin_pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=20)),
                ('fr_code', models.CharField(max_length=10)),
                ('eng_name', models.CharField(max_length=50, null=True)),
                ('up_station', models.CharField(default='', max_length=20, null=True)),
                ('down_station', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'ordering': ('fr_code',),
            },
        ),
        migrations.CreateModel(
            name='SubwayLandmarkPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(default='Station Not Set', max_length=20)),
                ('name', models.CharField(default='Landmark Not Set', max_length=50)),
                ('left', models.CharField(default='', max_length=20)),
                ('right', models.CharField(default='', max_length=20)),
                ('qr_file_name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=100)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subway.Subway')),
            ],
        ),
        migrations.AddField(
            model_name='subway',
            name='landmarks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subway.SubwayLandmarkPoint'),
        ),
        migrations.AddField(
            model_name='admins',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subway.Subway'),
        ),
    ]
