# Generated by Django 2.0.5 on 2018-06-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0002_subway_landmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20)),
                ('admin_pw', models.CharField(max_length=20)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subway.Subway')),
            ],
        ),
    ]
