# Generated by Django 2.0.5 on 2018-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0003_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='subway',
            name='down_station',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subway',
            name='up_station',
            field=models.CharField(default='', max_length=20),
        ),
    ]
