# Generated by Django 2.0.5 on 2018-06-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0004_auto_20180606_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subway',
            name='down_station',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subway',
            name='up_station',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
