# Generated by Django 2.0.5 on 2018-06-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0005_auto_20180606_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Admins',
        ),
    ]
