# Generated by Django 2.0.5 on 2018-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0006_auto_20180607_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaylandmarkpoint',
            name='left',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='subwaylandmarkpoint',
            name='right',
            field=models.CharField(default='', max_length=5),
        ),
    ]
