# Generated by Django 2.0.5 on 2018-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0007_auto_20180609_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaylandmarkpoint',
            name='left',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subwaylandmarkpoint',
            name='right',
            field=models.CharField(default='', max_length=20),
        ),
    ]
