# Generated by Django 2.0.5 on 2018-06-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0010_subwaylandmarkpoint_landmark_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subwaylandmarkpoint',
            old_name='landmark_name',
            new_name='name',
        ),
    ]
