# Generated by Django 2.0.5 on 2018-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0012_auto_20180610_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaylandmarkpoint',
            name='station_name',
            field=models.CharField(default='Station Not Set', max_length=20),
        ),
    ]
