# Generated by Django 2.0.5 on 2018-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0013_auto_20180610_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaylandmarkpoint',
            name='qr',
            field=models.ImageField(null=True, upload_to='subway/qr_images'),
        ),
    ]
