# Generated by Django 2.0.5 on 2018-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0014_subwaylandmarkpoint_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaylandmarkpoint',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
