# Generated by Django 2.0.5 on 2018-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0015_subwaylandmarkpoint_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaylandmarkpoint',
            name='qr',
            field=models.ImageField(default='static/qr_images/no-img.jpg', upload_to='static/qr_images'),
        ),
    ]
