# Generated by Django 2.0.5 on 2018-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0016_auto_20180611_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaylandmarkpoint',
            name='qr',
            field=models.ImageField(null=True, upload_to='qrs/'),
        ),
    ]
