# Generated by Django 2.0.5 on 2018-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0017_auto_20180611_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwaylandmarkpoint',
            name='qr',
        ),
        migrations.AddField(
            model_name='subwaylandmarkpoint',
            name='qr_file_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
